version: '3'
services:
  web:
    image: boloagegit/todolist-backend:${TAG:-latest}
    build: .
    depends_on:
      - db
    ports:
      - "5503:5505"
    container_name: todolist-backend
    links:
      - "db:db"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/todolist
      SPRING_DATASOURCE_USERNAME: todolist
      SPRING_DATASOURCE_PASSWORD: 123456
  db:
    image: 'mariadb:10'
    ports:
      - '5506:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'todolist'
      MYSQL_USER: 'todolist'
      MYSQL_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - 'todolistdb:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p 123456"]
      retries: 3
      timeout: 5s
    container_name: todolist-db
volumes:
  todolistdb:
    driver: local
