version: '3'
services:
  db:
    image: 'mariadb:10'
    ports:
      - '5506:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'todolist'
      MYSQL_USER: 'todolist'
      MYSQL_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - 'todolistdb:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p 123456"]
      retries: 3
      timeout: 5s
volumes:
  todolistdb:
    driver: local
